/*
Script Purpose:
The purpose of this script is about comparing the measure values across different categories
and dimensions. This outlines the importance of different categories within the business
*/


--Find the total customers by countries
SELECT COUNT(customer_key) total_customers, country FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC

--Find total customers by gender
SELECT COUNT(customer_key) total_customers, gender FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC

--Find the total products by category
SELECT COUNT(product_key) total_products, category FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC

--What is the average cost in each category?
SELECT AVG(cost) avg_cost, category FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC

--What is the total revenue generated for each customer?
SELECT SUM(s.sales_amount) total_revenue, p.category FROM gold.fact_sales s
LEFT JOIN gold.dim_products p
ON p.product_key = s.product_key
GROUP BY p.category
ORDER BY total_revenue DESC

--Find the total revenue that is generated by each customer?
SELECT  c.customer_key, c.first_name, c.last_name, 
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY 
c.customer_key,
c.first_name,
c.last_name
ORDER BY total_revenue DESC

--What is the distribution of sold items across countries?
SELECT c.country, SUM(f.quantity) total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC